version: '2'

services:

  mariadb:
    build: ./storage/dockerfiles/mariadb
    volumes_from:
      - volumes_data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: lhzbxx
      MYSQL_PASSWORD: 5120309188
      MYSQL_ROOT_PASSWORD: F1203005_5120309188_LuHao
    container_name: Site_mariadb

  redis:
    build: ./storage/dockerfiles/redis
    volumes_from:
      - volumes_data
    ports:
      - "6379:6379"
    container_name: Site_redis

  volumes_data:
    image: tianon/true
    volumes:
      - ./storage/data/mysql:/var/lib/mysql
      - ./storage/data/redis:/data
    container_name: Site_data