LOAD DATA LOCAL INFILE  'classpath:/data/products.vbsv'
INTO TABLE product
FIELDS TERMINATED BY '|'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE  'classpath:/data/faq.csv'
INTO TABLE faq
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(answer, question, serial_id);